# dev options
debug: true

# scene
scene: gibson # = initiates StaticIndoorScene
scene_id: Rs # = Name of scene, passed to the constructor of above class ^
build_graph: true
load_texture: true
pybullet_load_texture: true
trav_map_type: no_obj
trav_map_resolution: 0.1
trav_map_erosion: 2
should_open_all_doors: true

# domain randomization
texture_randomization_freq: null
object_randomization_freq: null

# robot
robot:
  name: Turtlebot
  action_type: continuous
  action_normalize: true
  base_name: null
  scale: 1.0
  self_collision: false
  rendering_params: null
  controller_config:
    base:
      name: DifferentialDriveController

# task
task: go_to_object
target_dist_min: 1.0
target_dist_max: 10.0
random_nav: true # Picks a random position through the whole scene instead of using spawn_bounds
goal_format: polar
task_obs_dim: 4 # 2 if no target position ...Changed from 4 because i am excluding the goal's position
initial_pos: [-2.7, 1.1, 0]
#initial_pos: [0, 0, 0]
target_pos: [1, 1, 0]
# spawn_bounds: [[-1, -1], [1, 1]] # [[lower_x, lower_y], [upper_x, upper_y]] ## example [[-1, -1], [1, 1]]
# spawn_bounds: [[-3.7, -3.2], [1.7, 2.6]] # Rs scene
spawn_bounds: [[-2,7, -0.7],[5.0, 12.5]] # Plessis scene
# spawn_bounds: [
  # [[-2.7, 1.1], [-2.8, 0.9]],
  # [[-2.7, 1.1], [-2.8, 0.9]],
  # [[-2.7, 1.1], [-2.8, 0.9]],
  # [[-2.7, 1.1], [-2.8, 0.9]]
# ]

# reward
reward_type: geodesic
success_reward: 10.0
potential_reward_weight: 1.0
collision_reward_weight: -0.1

# discount factor
discount_factor: 0.99

# termination condition
dist_tol: 0.36  # body width
max_step: 800
max_collisions_allowed: 500

# misc config
initial_pos_z_offset: 0.1
collision_ignore_link_a_ids: [1, 2, 3, 4]  # ignore collisions with these robot links

# sensor spec
# output: [task_obs, rgb, depth, scan]
output: [task_obs, scan, rgb]
# image
# ASUS Xtion PRO LIVE
# https://www.asus.com/us/3D-Sensor/Xtion_PRO_LIVE
fisheye: false
image_width: 160 # 640
image_height: 120 # 480
vertical_fov: 45
# depth
depth_low: 0.8
depth_high: 3.5
# scan
# Hokuyo URG-04LX-UG01
# https://www.hokuyo-aut.jp/search/single.php?serial=166
# n_horizontal_rays is originally 683, sub-sampled 1/3
n_horizontal_rays: 228
n_vertical_beams: 1
laser_linear_range: 5.6
laser_angular_range: 240.0
min_laser_dist: 0.05
laser_link_name: scan_link

# sensor noise
depth_noise_rate: 0.0
scan_noise_rate: 0.0

# visual objects
visible_target: false
visible_path: false
